spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://users-db:5432/user-service
    username: user-service
    password: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'user-service'
      paths-to-match: /api/users/**

logging:
  level:
    root: INFO
    com.pii: DEBUG
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.springframework.transaction: TRACE
#    org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: DEBUG
