spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://users-db:5432/user-service
    username: user-service
    password: user-service
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    discovery:
      enabled: true
#    loadbalancer:
#      enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

logging:
  level:
    root: INFO
    com.pii: DEBUG
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.jdbc.datasource: DEBUG
#    org.springframework.transaction: TRACE
#    org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: DEBUG
