spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://users-db:5432/user-service
    username: user-service
    password: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    com.pii.organization_system: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: DEBUG
