version: '3.8'

services:
  users-db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: user-service
      POSTGRES_DB: user-service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - users-db
    restart: on-failure

volumes:
  postgres_data:
