services:
  config-service:
    build:
      context: ./services/config-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - backend
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  discovery-service:
    build:
      context: ./services/discovery-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health || exit 1" ]
      interval: 10s
      timeout: 20s
      retries: 10
    restart: unless-stopped

  users-db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: user-service
      POSTGRES_DB: user-service
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - users_data:/var/lib/postgresql/data
      - ./services/user-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user-service" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_started
      users-db:
        condition: service_healthy
      discovery-service:
        condition: service_started
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  companies-db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: company-service
      POSTGRES_PASSWORD: company-service
      POSTGRES_DB: company-service
    ports:
      - "5434:5432"
    networks:
      - backend
    volumes:
      - companies_data:/var/lib/postgresql/data
      - ./services/company-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U company-service" ]
      interval: 5s
      timeout: 5s
      retries: 5

  company-service:
    build:
      context: ./services/company-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_started
      companies-db:
        condition: service_healthy
      discovery-service:
        condition: service_started
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  gateway-service:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_started
      discovery-service:
        condition: service_started
      user-service:
        condition: service_started
      company-service:
        condition: service_started
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  users_data:
  companies_data:

networks:
  backend:
