spring:
  application:
    name: discovery-service

  config:
    import: optional:configserver:http://config-service:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
