spring:
  application:
    name: discovery-service

  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
