spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: file:/config-repo

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**

        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs

        - id: company-service-docs
          uri: lb://company-service
          predicates:
            - Path=/company-service/v3/api-docs
          filters:
            - RewritePath=/company-service/v3/api-docs, /v3/api-docs

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

server:
  port: 8080

springdoc:
  api-docs:
    groups:
      user-service:
        url: /user-service/v3/api-docs
      company-service:
        url: /company-service/v3/api-docs
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: company-service
        url: /company-service/v3/api-docs
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
