spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://localhost:5434/company-service
    username: company-service
    password: company-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    discovery:
      enabled: true
#    loadbalancer:
#      enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

logging:
  level:
    root: INFO
    com.pii: DEBUG
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG
    org.springframework.cloud.openfeign: DEBUG
#    org.springframework.transaction: TRACE
#    org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: DEBUG
